wsgi/openshift/customer/urls.py
from django.conf.urls import patterns, url

from customer import views

urlpatterns = patterns('',
    url(r'^$', views.Profile.as_view(), name='profile'),

    url(r'^register/$', views.Register.as_view(), name='register'),
    url(r'^register/complete/$',
        views.RegisterComplete.as_view(), name='register_complete'),

    url(r'^login/$', views.Login.as_view(), name='login'),
    url(r'^logout/$', views.Logout.as_view(), name='logout'),

    url(r'^hotline/$', views.Hotline.as_view(), name='hotline'),
    url(r'^hotline/complete/$',
        views.HotlineComplete.as_view(), name='hotline_complete'),

    url(r'^question/$', views.Question.as_view(), name='question'),
    url(r'^question/complete/$',
        views.QuestionComplete.as_view(), name='question_complete'),

    url(r'^order/$', views.Order.as_view(), name='order'),
)

wsgi/openshift/info/urls.py
from django.conf.urls import patterns, url

from info import views

urlpatterns = patterns('',
    url(r'^$', views.Home.as_view(), name='home'),

    url(r'^news/$', views.News.as_view(), name='news'),
    url(r'^news/(?P<year>\d{4})/$', views.News.as_view(), name='news'),

    url(r'^specoffers/$', views.SpecOffers.as_view(), name='specoffers'),
    url(r'^specoffers/(?P<state>active|finished|all)/$',
        views.SpecOffers.as_view(), name='specoffers'),

    url(r'^papers/$', views.Papers.as_view(), name='papers'),

    url(r'^(?P<slug>[\w-]+)/$', views.Page.as_view(), name='page'),
)

wsgi/openshift/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^customer/', include('customer.urls', namespace='customer')),
    url(r'', include('info.urls', namespace='info')),
)

wsgi/openshift/info/models.py
from django.db import models

class Page(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=100)
    text = models.TextField()

    def __str__(self):
        return self.name

class PublTextModel(models.Model):
    '''
    Published text and its publication date
    '''
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name='Publication date')
    #description = models.CharField(max_length=500, blank=True)

    def __str__(self):
        return self.frag_of_text()

    def frag_of_text(self):
        if len(self.text) > 100:
            frag = self.text.split('. ', 1)[0]
            if len(frag) > 100:
                return '{0}...'.format(frag[:100])
            return '{0}.'.format(frag)
        # Otherwise
        return self.text

    frag_of_text.admin_order_field = 'text'
    frag_of_text.short_description = 'Text'

    class Meta:
        abstract = True
        ordering = ['-created_at']

class News(PublTextModel):
    class Meta(PublTextModel.Meta):
        verbose_name_plural = 'news'

class SpecOffer(PublTextModel):
    finished = models.BooleanField(default=False)

    class Meta(PublTextModel.Meta):
        verbose_name = 'special offer'

wsgi/openshift/info/views.py
from django.http import Http404
#from django.utils.translation import ugettext_lazy as _

from datetime import datetime
from itertools import chain
from operator import attrgetter

from base.views import TemplateView, ListView, DetailView
from info import models

class Home(TemplateView):
    menu_item = 'home'
    template_name = 'info/home.html'

    ads_count = 6 # number of latest news and special offers

    def get_context_data(self, **kwargs):
        n = self.ads_count
        news_list = models.News.objects.extra(select={'tag': '"news"'})[:n]
        specoffers_list = \
            models.SpecOffer.objects.filter(finished=False) \
                                    .extra(select={'tag': '"specoffer"'})[:n]
        # Ads -- news and special offers
        ads = sorted(chain(news_list, specoffers_list),
                     key=attrgetter('created_at'), reverse=True)
        # Context
        data = super().get_context_data(**kwargs)
        data['last_ads'] = ads[:n] # latest news and special offers
        return data

class News(ListView):
    '''
    List of all news filtered by year
    '''
    menu_item = 'news'
    template_name = 'info/news.html'
    context_object_name = 'news_list' # name of the list in template
    #paginate_by = 10 # number of news on one page

    years = [] # list of available years
    year = None # filter

    def get_queryset(self):
        # Available datetimes
        dt_qset = models.News.objects.datetimes('created_at', 'year',
                                                order='DESC')
        self.years = [dt.year for dt in dt_qset]
        #
        if 'year' in self.kwargs:
            try:
                self.year = int(self.kwargs['year'])
            except ValueError:
                raise Http404()
        else:
            self.year = self.years[0] # last available year
        #
        return models.News.objects.filter(created_at__year=self.year)

    def get_context_data(self, **kwargs):
        # Context
        data = super().get_context_data(**kwargs)
        data['year'] = self.year # year of displayed news
        data['years'] = self.years # available years of all news
        return data

class SpecOffers(ListView):
    '''
    List of all special offers filtered by state
    '''
    menu_item = 'specoffers'
    template_name = 'info/specoffers.html'
    context_object_name = 'specoffers_list' # name of the list in template
    #paginate_by = 10 # number of special offers on one page

    state = 'active' # filter, active by default

    def get_queryset(self):
        # Available filters
        manager = models.SpecOffer.objects
        qset_by_state = {
            'active': (lambda: manager.filter(finished=False)),
            'finished': (lambda: manager.filter(finished=True)),
            'all': manager.all
        }
        # Current filter
        if 'state' in self.kwargs:
            self.state = self.kwargs['state']
        # Fetches special offers
        if self.state not in qset_by_state:
            raise Http404()
        return qset_by_state[self.state]()

    def get_context_data(self, **kwargs):
        # States menu section
        menu_states = [('active', 'действующие'),
                       ('finished', 'завершенные'),
                       ('all', 'все')]
        # Context
        data = super().get_context_data(**kwargs)
        menu = data.get('menu', {})
        menu.update({'states': ({'name': name, 'text': text}
                                for (name, text) in menu_states)})
        data['menu'] = menu # all main menus + states menu
        data['state'] = self.state # current state
        return data

class Page(DetailView):
    model = models.Page
    slug_field = 'name'

    template_name = 'info/page.html'
    context_object_name = 'page' # name of the object in template

    def get_object(self, queryset=None):
        if 'slug' in self.kwargs:
            self.menu_item = self.kwargs['slug']
        #
        if not self.menu_item:
            raise Http404()
        #
        return super().get_object(queryset)

class Papers(TemplateView):
    menu_item = 'papers'
    template_name = 'info/papers.html'

wsgi/openshift/info/templates/info/home.html
{% extends 'base.html' %}

{% block featured_content %}
  <div class="jumbotron board">
    <div class="container">
      <div class="row col-xs-12">
        <h1>Международные перевозки</h1>
      </div>
      <div class="row">
        <div class="col-md-8">
          <h2 class="text-success">Сервис логистических услуг</h2>
          <ul class="list-unstyled">
            <li><span class="glyphicon glyphicon-cloud"></span>&nbsp;&nbsp;Весь комплекс предоставляемых услуг&nbsp;&mdash; онлайн</li>
            <li><span class="glyphicon glyphicon-send"></span>&nbsp;&nbsp;Активная обратная связь в любое время</li>
            <li><span class="glyphicon glyphicon-eye-close"></span>&nbsp;&nbsp;Конфиденциальность информации и защита данных</li>
            <li><span class="glyphicon glyphicon-phone"></span>&nbsp;&nbsp;Поддержка десктопов и мобильных устройств</li>
          </ul>
        </div>
        <div class="col-md-4">
          <h2 class="text-success">Личный кабинет</h2>
          <p>Заказывайте и отслеживайте перевозки, рассчитывайте их стоимость, управляйте доставками и выписывайте счета.</p>
          <p><a href="{% url 'customer:register' %}" role="button" class="btn btn-primary btn-lg">Создать личный кабинет &rarr;</a></p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-4">
      <h2>Что нового</h2>
      <div class="txt">
  {% for ad in last_ads %}
        <p><span class="label label-{% ifequal ad.tag 'specoffer' %}success{% else %}info{% endifequal %}">{{ ad.created_at|date:'d.m' }}</span> {{ ad.text|safe }}</p>
  {% empty %}
        <p>Новостей пока нет :(</p>
  {% endfor %}
      </div>
    </div>
    <div class="col-md-4">
      <h2>Помощь экспертов</h2>
      <!--p>Обычно у внешнеторгового груза целый пакет сопроводительных документов, работа с которыми требует специальных знаний и опыт. Вы можете воспользоваться услугами наших экспертов, которые помимо таможенного оформления помогут оформить разрешительные документы и заключения, а также подготовить коммерческую и товаросопроводительную документацию, проконсультируют вас в вопросах налогообложения внешнеэкономических операций.</p-->
      <div class="txt">
        <p>Мы выполняем операции по таможенному оформлению:</p>
        <ul>
          <li>декларирование товаров, составление ГТД и сопутствующих документов;</li>
          <li>предоставление таможенному органу необходимых документов и дополнительных сведений;</li>
          <li>предъявление декларируемых товаров;</li>
          <li>прочие операции, необходимые для таможенного оформления и контроля.</li>
        </ul>
      </div>
      <p><a href="{% url 'customer:question' %}" role="button" class="btn btn-default">Оставить заявку &rarr;</a> или <a href="{% url 'customer:hotline' %}" class="txt">задать вопрос</a></p>
    </div>
    <div class="col-md-4">
      <h2>Доставка груза</h2>
      <div class="txt">
        <p>Вы можете заказывать в режиме онлайн:</p>
        <ul>
          <li>доставки личных вещей и товаров интернет-магазинов;</li>
          <li>перевозки негабаритных и тяжеловесных грузов;</li>
          <li>доставки опасных грузов;</li>
          <li>переезды грузов;</li>
          <li>перевозки под таможенным контролем;</li>
          <li>доставки сборных грузов;</li>
          <li>мультимодальные перевозки.</li>
        </ul>
      </div>
      <p><a href="{% url 'customer:order' %}" role="button" class="btn btn-default">Заказать доставку &rarr;</a></p>
    </div>
  </div>
{% endblock %}

wsgi/openshift/info/templates/info/news.html
{% extends 'base.html' %}

{% block title %}Новости «Деливери»{% endblock %}

{% block roof %}
  <link href="/static/styles/offcanvas.css" rel="stylesheet">
{% endblock %}

{% block content %}
  <div class="row row-offcanvas row-offcanvas-right">
    <div class="col-xs-12 col-sm-9">
      <p class="pull-right visible-xs"><button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Другие годы</button></p>
  {% if news_list %}
      <p class="lead">Новости за {{ year }}-й год</p>
    {% regroup news_list by created_at.month as news_by_month %}
    {% for news_of_month in news_by_month %}
      {% if forloop.first %}
      <div class="jumbotron">
      {% else %}
      <div class="col-6 col-sm-6">
      {% endif %}
        <dl class="dl-horizontal">
      {% for news in news_of_month.list %}
        {% with dt=news.created_at %}
          {% ifchanged dt.day %}
          <dt>{{ dt|date:'j E' }}</dt>
          {% else %}
          <dt></dt>
          {% endifchanged %}
        {% endwith %}
          <dd>{{ news.text|safe }}</dd>
      {% endfor %}
        </dl>
      </div>
      {% ifnotequal forloop.first forloop.last %}
        {% if forloop.first %}<div class="row">{% else %}</div>{% endif %}
      {% endifnotequal %}
    {% endfor %}
  {% else %}
    <p class="lead">Новости за {{ year }}-й год отсутствуют.</p>
  {% endif %}
    </div>
    <div role="navigation" id="sidebar" class="col-xs-6 col-sm-3 sidebar-offcanvas">
      <ul class="nav nav-sidebar">
  {% for yr in years %}
    {% ifequal yr year %}
        <li class="active"><span>{{ yr }}</span></li>
    {% else %}
        <li><a href="{% url 'info:news' yr %}"><span>{{ yr }}</span></a></li>
    {% endifequal %}
  {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

{% block ground %}
  <script src="/static/scripts/offcanvas.js"></script>
{% endblock %}

wsgi/openshift/info/templates/info/page.html
{% extends 'base.html' %}

{% block title %}{{ page.title }}{% endblock %}

{% block content %}{{ page.text|safe }}{% endblock %}

wsgi/openshift/info/templates/info/papers.html
{% extends 'base.html' %}

{% block title %}Документы «Деливери»{% endblock %}

{% block content %}
<h1>Документация</h1>
<p>Документы по таможенному оформлению, формы товарно-транспортных накладных, ...</p>
{% endblock %}

wsgi/openshift/info/templates/info/specoffers.html
{% extends 'base.html' %}

{% block title %}Спецпредложения «Деливери»{% endblock %}

{% block roof %}
  <link href="/static/styles/offcanvas.css" rel="stylesheet">
{% endblock %}

{% block content %}
  <div class="row row-offcanvas row-offcanvas-right">
    <div class="col-xs-12 col-sm-9">
      <p class="pull-right visible-xs"><button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Другие акции</button></p>
  {% if specoffers_list %}
    {% if state == 'active' %}
      <p class="lead">Действующие предложения</p>
    {% elif state == 'finished' %}
      <p class="lead">Завершенные акции</p>
    {% else %}
      <p class="lead">Специальные предложения</p>
    {% endif %}
    {% regroup specoffers_list by created_at.year as specoffers_by_year %}
    {% for specoffers_of_year in specoffers_by_year %}
      {% if forloop.first %}
      <div class="jumbotron">
      {% else %}
      <div class="col-6 col-sm-6">
      {% endif %}
        <dl class="dl-horizontal">
      {% for specoffer in specoffers_of_year.list %}
        {% with dt=specoffer.created_at %}
          {% ifchanged dt.month dt.day %}
          <dt>{{ dt|date:'j E Y' }}</dt>
          {% else %}
          <dt></dt>
          {% endifchanged %}
        {% endwith %}
          <dd>{{ specoffer.text|safe }}{% if state == 'all' and specoffer.finished %} <span class="label label-default">акция завершена</span>{% endif %}</dd>
      {% endfor %}
        </dl>
      </div>
      {% ifnotequal forloop.first forloop.last %}
        {% if forloop.first %}<div class="row">{% else %}</div>{% endif %}
      {% endifnotequal %}
    {% endfor %}
  {% else %}
    {% if state == 'active' %}
      <p class="lead">Действующие предложения отсутствуют.</p>
    {% elif state == 'finished' %}
      <p class="lead">Завершенные акции отсутствуют.</p>
    {% else %}
      <p class="lead">Спецпредложения отсутствуют.</p>
    {% endif %}
  {% endif %}
    </div>
    <div role="navigation" id="sidebar" class="col-xs-6 col-sm-3 sidebar-offcanvas">
      <ul class="nav nav-sidebar">
  {% for item in menu.states %}
    {% ifequal state item.name %}
        <li class="active"><span>{{ item.text }}</span></li>
    {% else %}
        <li><a href="{% url 'info:specoffers' item.name %}"><span>{{ item.text }}</span></a></li>
    {% endifequal %}
  {% endfor %}
      </ul>
    </div>
  </div>
{% endblock %}

{% block ground %}
  <script src="/static/scripts/offcanvas.js"></script>
{% endblock %}