wsgi/openshift/customer/urls.py
from django.conf.urls import patterns, url

from customer import views

urlpatterns = patterns('',
    url(r'^$', views.Profile.as_view(), name='profile'),

    url(r'^register/$', views.Register.as_view(), name='register'),
    url(r'^register/complete/$',
        views.RegisterComplete.as_view(), name='register_complete'),

    url(r'^login/$', views.Login.as_view(), name='login'),
    url(r'^logout/$', views.Logout.as_view(), name='logout'),

    url(r'^hotline/$', views.Hotline.as_view(), name='hotline'),
    url(r'^hotline/complete/$',
        views.HotlineComplete.as_view(), name='hotline_complete'),

    url(r'^question/$', views.Question.as_view(), name='question'),
    url(r'^question/complete/$',
        views.QuestionComplete.as_view(), name='question_complete'),

    url(r'^order/$', views.Order.as_view(), name='order'),
)

wsgi/openshift/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^customer/', include('customer.urls', namespace='customer')),
    url(r'', include('info.urls', namespace='info')),
)

wsgi/openshift/customer/models.py
from django.db import models
from django.contrib.auth.models import User
#from django.utils.translation import ugettext_lazy as _

class DictModel(models.Model):
    '''
    Simple dictionary
    '''
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        abstract = True

class Profile(models.Model):
    user = models.ForeignKey(User, unique=True)
    phone = models.CharField(max_length=30, blank=True,
                             verbose_name='Phone number')

    def __str__(self):
        return '{0} {1}'.format(self.user.first_name, self.user.last_name)

class QuestionKind(DictModel):
    pass

class QuestionStatus(DictModel):
    class Meta:
        verbose_name_plural = 'question statuses'

class Question(models.Model):
    profile = models.ForeignKey(Profile)
    number = models.PositiveIntegerField()
    kind = models.ForeignKey(QuestionKind)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name='Question date')
    status = models.ForeignKey(QuestionStatus)

    def __str__(self):
        return '{0} - No. {1}'.format(self.profile, self.number)

    class Meta:
        ordering = ['-created_at']

class OrderKind(DictModel):
    pass

class OrderStatus(DictModel):
    class Meta:
        verbose_name_plural = 'order statuses'

class Order(models.Model):
    profile = models.ForeignKey(Profile)
    number = models.PositiveIntegerField()
    kind = models.ForeignKey(OrderKind)
    dispatch_address = models.CharField(max_length=500)
    delivery_address = models.CharField(max_length=500)
    note = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name='Order date')
    status = models.ForeignKey(OrderStatus)

    def __str__(self):
        return '{0} - No. {1}'.format(self.profile, self.number)

    class Meta:
        ordering = ['-created_at']

class DangerCategory(DictModel):
    class Meta:
        verbose_name = 'dangerous goods class'
        verbose_name_plural = 'dangerous goods classes'

class Cargo(models.Model):
    order = models.ForeignKey(Order)
    number = models.PositiveIntegerField()
    number_of_units = models.PositiveIntegerField()
    number_of_boxes = models.PositiveIntegerField()
    weight_nett = models.FloatField()
    weight_gross = models.FloatField()
    length = models.FloatField()
    width = models.FloatField()
    height = models.FloatField()
    description = models.TextField(blank=True)
    danger_category = models.ForeignKey(DangerCategory)

    def __str__(self):
        return '{0}. Cargo {1}'.format(self.order, self.number)

wsgi/openshift/customer/forms.py
from django import forms
from django.core.mail import send_mail
from django.contrib.auth import authenticate
from django.contrib.auth.models import User
#from django.utils.translation import ugettext_lazy as _

from customer import models

class Form(forms.Form):
    def has_field_errors(self):
        has_non_field_errors = bool(self.non_field_errors())
        return (len(self.errors) > int(has_non_field_errors))

class Register(Form):
    first_name = forms.CharField(max_length=30, label='Имя')
    last_name = forms.CharField(max_length=30, label='Фамилия')
    email = forms.EmailField(label='Электронная почта')
    password = forms.CharField(widget=forms.PasswordInput,
                               label='Придумайте пароль')
    password_confirm = forms.CharField(widget=forms.PasswordInput,
                                       label='Повторите пароль')
    phone = forms.RegexField(regex=r'^(\+\d{1,2}\s)?\(?\d{3}\)?[\s.-]\d{3}' \
                                    '[\s.-]\d{4}$',
                             error_messages={
                                 'invalid': 'Допускаются следующие формы ' \
                                            'номера телефона: ' \
                                            '123-456-7890, ' \
                                            '(123) 456-7890, ' \
                                            '123 456 7890, ' \
                                            '123.456.7890, ' \
                                            '+91 (123) 456-7890.'},
                             required=False, max_length=30,
                             label='Номер телефона')
    """
    username = forms.RegexField(regex=r'^[\w.@+-]+$', max_length=30,
                                error_messages={
                                    'invalid': 'This value may contain ' \
                                               'only letters, numbers and ' \
                                               '@/./+/-/_ characters.'})
    human_test = forms.ChoiceField(label='Are you human?')
    """

    def clean_email(self):
        '''
        Checks that the supplied email address is unique for the site
        '''
        email = self.cleaned_data['email']
        if User.objects.filter(email__iexact=email):
            raise forms.ValidationError('Этот адрес электронной почты уже ' \
                                        'используется. Пожалуйста, введите ' \
                                        'другой адрес.')
        return email

    """
    def clean_username(self):
        '''
        Checks that the username is not already in use
        '''
        if User.objects.filter(username__iexact=self.cleaned_data['username']):
            raise forms.ValidationError('A user with that username already ' \
                                        'exists.')
        return self.cleaned_data['username']
    """

    """
    def clean_human_test(self):
        '''
        Checks that the user is human
        '''
        if not self.cleaned_data['human_test']:
            raise forms.ValidationError('Robot shall not pass! Try again.')
        return self.cleaned_data['human_test']
    """

    def clean(self):
        '''
        Checks that the two password entries match
        '''
        data = self.cleaned_data
        first = data['password']
        second = data['password_confirm']
        if first and second and (first != second):
            raise forms.ValidationError('Подтверждение не совпадает с ' \
                                        'паролем.')
        return data

    def create_profile(self, email_user=True):
        data = self.cleaned_data
        fields = {
            'username': data['email'],
            'first_name': data['first_name'],
            'last_name': data['last_name'],
            'email': data['email'],
            'password': data['password']
        }
        phone = data['phone']
        # Creates new user and profile
        user = User.objects.create_user(**fields)
        models.Profile.objects.create(user=user, phone=phone)
        # Notifies the user
        if email_user:
            subject = "Welcome to Delivery Int'l"
            message = 'Hello, {0}!\n\n' \
                      'Thank you for registering.\n\n' \
                      'Here bellow you can find your credentials.\n\n' \
                      'E-mail: {1}\n' \
                      'Password: Your Set Password\n\n' \
                      'Regards,\n\n' \
                      "-- Delivery Int'l\n".format(user.first_name, user.email)
            user.email_user(subject, message)

    def validate_auth(self):
        data = self.cleaned_data
        return authenticate(username=data['email'], password=data['password'])

class Login(Form):
    email = forms.EmailField(label='Электронная почта')
    password = forms.CharField(widget=forms.PasswordInput, label='Пароль')

    auth_user = None # authenticated user

    def clean_email(self):
        '''
        Checks that some user has the supplied email address
        '''
        email = self.cleaned_data['email']
        if not User.objects.filter(email__iexact=email):
            raise forms.ValidationError('Учётной записи с таким адресом ' \
                                        'электронной почты не существует.')
        return email

    def clean_password(self):
        '''
        Authenticates the user with email address as username
        '''
        data = self.cleaned_data
        if 'email' not in data:
            return None
        #
        self.auth_user = authenticate(username=data['email'],
                                      password=data['password'])
        if not self.auth_user:
            raise forms.ValidationError('Неправильный пароль. Попробуйте ' \
                                        'ввести еще раз.')
        #
        return data['password']

    def clean(self):
        if not self.auth_user:
            return None
        # Checks other things
        if not self.auth_user.is_active:
            raise forms.ValidationError('Учетная запись заблокирована.')
        return self.cleaned_data

class Hotline(Form):
    subject = forms.CharField(required=False, max_length=100,
                              label='Тема вашего сообщения')
    email = forms.EmailField(label='Электронная почта (для ответа на ' \
                                   'сообщение)')
    text = forms.CharField(widget=forms.Textarea,
                           label='Ваш вопрос, предложения или замечания')

    """
    auth_user = None # authenticated user

    def __init__(self, *args, **kwargs):
        self.auth_user = kwargs.pop('request').user
        super().__init__(*args, **kwargs)
    """

    """
    def clean_email(self):
        '''
        Checks that the supplied email address is unique for the site
        '''
        email = self.cleaned_data['email']
        if User.objects.filter(email__iexact=email):
            raise forms.ValidationError('This email address is already in ' \
                                        'use. Please supply a different ' \
                                        'email address.')
        return email
    """

    def clean_text(self):
        text = self.cleaned_data['text']
        num_words = len(text.split())
        if num_words < 4:
            raise forms.ValidationError('Напишите, пожалуйста, больше слов.')
        return text

    def send(self, request, email_user=False):
        data = self.cleaned_data
        subject = data.get('subject', 'Hotline')
        text = data['text']
        email = data['email']
        # Sends the question to operator
        #send_mail(subject, message=text, from_email=email,
        #          recipient_list=['hotline@delivery-international.com'])
        # Sends copy of the question to user
        if email_user:
            subject = "Question to Delivery Int'l: {0}".format(subject)
            user = request.user
            if user:
                message = 'Hello, {0}!\n\nYour message:\n{1}' \
                          .format(user.first_name, text)
                user.email_user(subject, message)
            else:
                message = 'Hello!\n\nYour message:\n{1}'.format(text)
                send_mail(subject, message,
                          from_email='hotline@delivery-international.com',
                          recipient_list=[email])

class Question(Form):
    kind = forms.ModelChoiceField(queryset=models.QuestionKind.objects.all(),
                                  empty_label='(Нет данных)',
                                  label='Тип задачи&nbsp;&mdash;')
    text = forms.CharField(widget=forms.Textarea,
                           label='Ваша проблема, описание задачи, условия ' \
                                 'и сроки')

    def clean_text(self):
        text = self.cleaned_data['text']
        num_words = len(text.split())
        if num_words < 8:
            raise forms.ValidationError('Опишите вашу проблему подробнее, ' \
                                        'укажите по возможности условия и ' \
                                        'сроки выполнения задач.')
        return text

    def send(self, request, email_user=False):
        kind = self.cleaned_data['kind']
        text = self.cleaned_data['text']
        status = models.QuestionStatus.objects.get(pk=1)
        # Creates the question
        user = request.user
        profile = models.Profile.objects.get(user=user)
        models.Question.objects.create(profile=profile, number=0, kind=kind,
                                       text=text, status=status)
        # Sends the question to expert
        #send_mail(subject='Question to expert: {0}'.format(kind.name),
        #          message=text, from_email=user.email,
        #          recipient_list=['expert@delivery-international.com'])
        # Sends copy of the question to user
        if email_user:
            subject = "Question to expert of Delivery Int'l: {0}" \

wsgi/openshift/customer/views.py
from django.contrib.auth import login, logout

from base.views import LoginRequiredMixin, AnonymousRequiredMixin, \
                       RedirectionMixin, TemplateView, FormView
from customer import models, forms

class Profile(LoginRequiredMixin, TemplateView):
    menu_item = 'profile'
    template_name = 'customer/profile.html'

    def get_context_data(self, **kwargs):
        user = self.request.user
        # Context
        data = super().get_context_data(**kwargs)
        data['orders'] = models.Order.objects.filter(profile__user=user)
        data['questions'] = models.Question.objects.filter(profile__user=user)
        return data

class Register(AnonymousRequiredMixin, RedirectionMixin, FormView):
    form_class = forms.Register

    template_name = 'customer/register.html'
    success_url = '/customer/register/complete/'

    def form_valid(self, form):
        form.create_profile(email_user=False)
        # Login after registration
        auth_user = form.validate_auth()
        if auth_user:
            login(self.request, auth_user)
        #
        return super().form_valid(form)

class RegisterComplete(LoginRequiredMixin, TemplateView):
    template_name = 'customer/register_complete.html'

class Login(AnonymousRequiredMixin, RedirectionMixin, FormView):
    form_class = forms.Login

    menu_item = 'login'
    template_name = 'customer/login.html'
    success_url = '/customer/' # redirect to profile page

    def form_valid(self, form):
        if form.auth_user:
            login(self.request, form.auth_user)
        #
        return super().form_valid(form)

class Logout(LoginRequiredMixin, TemplateView):
    menu_item = 'logout'
    template_name = 'customer/logout.html'

    def get_context_data(self, **kwargs):
        logout(self.request)
        return super().get_context_data(**kwargs)

class Hotline(FormView):
    form_class = forms.Hotline

    template_name = 'customer/hotline.html'
    success_url = '/customer/hotline/complete/'

    """
    def get_form_kwargs(self):
        '''
        Adds the request to the kwargs
        '''
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs
    """

    def form_valid(self, form):
        form.send(self.request)
        return super().form_valid(form)

class HotlineComplete(TemplateView):
    template_name = 'customer/hotline_complete.html'

class Question(LoginRequiredMixin, FormView):
    form_class = forms.Question

    template_name = 'customer/question.html'
    success_url = '/customer/question/complete/'

    def form_valid(self, form):
        form.send(self.request)
        return super().form_valid(form)

class QuestionComplete(LoginRequiredMixin, TemplateView):
    template_name = 'customer/question_complete.html'

class Order(LoginRequiredMixin, FormView):
    form_class = forms.Order

    template_name = 'customer/order.html'
    success_url = '/customer/'

    def form_valid(self, form):
        form.send(self.request)
        return super().form_valid(form)

wsgi/openshift/customer/templates/customer/hotline.html
{% extends 'base.html' %}
{% load boots %}

{% block title %}Обратная связь с «Деливери»{% endblock %}

{% block roof %}
  <link href="/static/styles/forms.css" rel="stylesheet">
  {% if form.has_field_errors %}
  <link href="/static/styles/form_errors.css" rel="stylesheet">
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <form role="form" class="form-solid" action="" method="post">{% csrf_token %}
        <h2>Обратная связь</h2>
        <p>Задайте вопрос или выскажите ваши предложения</p>
        {% b_input form.subject 'autofocus' type='text' spec_class='first' %}
        {% b_input form.email type='email' %}
        {% b_textarea form.text rows='10' spec_class='last' %}
        <button type="submit" class="btn btn-lg btn-primary btn-block">Отправить</button>
      </form>
    </div>
  </div>
{% endblock %}

{% block ground %}
  {% if form.has_field_errors %}
  <script src="/static/scripts/form_errors.js"></script>
  {% endif %}
{% endblock %}

wsgi/openshift/customer/templates/customer/hotline_complete.html
{% extends 'base.html' %}

{% block title %}Обратная связь с «Деливери»{% endblock %}

{% block content %}
  <p class="lead page-informing">Сообщение успешно отправлено на «Горячую линию».</p>
{% endblock %}

wsgi/openshift/customer/templates/customer/login.html
{% extends 'base.html' %}
{% load boots %}

{% block title %}Личный кабинет «Мой Деливери»{% endblock %}

{% block roof %}
  <link href="/static/styles/forms.css" rel="stylesheet">
  {% if form.has_field_errors %}
  <link href="/static/styles/form_errors.css" rel="stylesheet">
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
      <div class="form-heading">
        <h2>Вход в личный кабинет</h2>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
      <form role="form" class="form-solid" action="" method="post">{% csrf_token %} 
  {% if form.non_field_errors %}
        <div id="non_field_alert" class="alert alert-danger alert-dismissable fade in">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    {% for error in form.non_field_errors %}
          <p>{{ error }}</p>
    {% endfor %}
        </div>
  {% endif %}
        {% b_input form.email 'autofocus' type='email' spec_class='first' %}
        {% b_input form.password type='password' spec_class='last' %}
        <button type="submit" class="btn btn-lg btn-primary btn-block">Войти</button>
      </form>
    </div>
    <div class="col-sm-3 col-md-4">
      <div class="form-addon">
        <div class="well well-sm">
          <p class="last"><a href="{% url 'customer:register' %}{% if next %}?next={{ next }}{% endif %}" class="txt">Создайте личный кабинет</a>, если вы здесь впервые.</p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

{% block ground %}
  {% if form.has_field_errors %}
  <script src="/static/scripts/form_errors.js"></script>
  {% endif %}
{% endblock %}

wsgi/openshift/customer/templates/customer/logout.html
{% extends 'base.html' %}

{% block title %}Личный кабинет «Мой Деливери»{% endblock %}

{% block content %}
  <p class="lead page-informing">Вы вышли из личного кабинета.</p>
{% endblock %}

wsgi/openshift/customer/templates/customer/order.html
{% extends 'base.html' %}
{% load boots %}

{% block title %}Заказ доставки в «Моём Деливери»{% endblock %}

{% block roof %}
  <link href="/static/styles/forms.css" rel="stylesheet">
  {% if form.has_field_errors %}
  <link href="/static/styles/form_errors.css" rel="stylesheet">
  {% endif %}
  <link href="/static/styles/choicebox.css" rel="stylesheet">
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <form role="form" class="form-normal" action="" method="post">{% csrf_token %}
        <h2>Доставка груза</h2>
        <p>Укажите основные сведения о перевозке и информацию о грузе</p>
        {% b_choicebox form.kind 'autofocus' %}
        <p class="form-control-static">Адреса перевозки</p>
        <div class="row">
          <div class="col-sm-6">
            <div class="input-group">
              <span class="input-group-addon">{{ form.dispatch_address.label }}</span>
              {% b_input form.dispatch_address 'unlabeled' type='text' %}
            </div>
          </div>
          <div class="col-sm-6">
            <div class="input-group">
              <span class="input-group-addon">{{ form.delivery_address.label }}</span>
              {% b_input form.delivery_address 'unlabeled' type='text' %}
            </div>
          </div>
        </div>
        <p class="form-control-static">Количество</p>
        <div class="row">
          <div class="col-xs-6">
            <div class="input-group">
              <span class="input-group-addon">{{ form.number_of_units.label }}</span>
              {% b_input form.number_of_units 'unlabeled' type='number' %}
            </div>
          </div>
          <div class="col-xs-6">
            <div class="input-group">
              <span class="input-group-addon">{{ form.number_of_boxes.label }}</span>
              {% b_input form.number_of_boxes 'unlabeled' type='number' %}
            </div>
          </div>
        </div>
        <p class="form-control-static">Вес коробки в кг</p>
        <div class="row">
          <div class="col-xs-6">
            <div class="input-group">
              <span class="input-group-addon">{{ form.weight_nett.label }}</span>
              {% b_input form.weight_nett 'unlabeled' type='number' %}
              <!-- min="0.1" step="any" -->
            </div>
          </div>
          <div class="col-xs-6">
            <div class="input-group">
              <span class="input-group-addon">{{ form.weight_gross.label }}</span>
              {% b_input form.weight_gross 'unlabeled' type='number' %}
            </div>
          </div>
        </div>
        <p class="form-control-static">Размеры коробки в см</p>
        <div class="row">
          <div class="col-xs-4">
            <div class="input-group">
              <span class="input-group-addon">Ш</span>
              {% b_input form.width type='number' %}
            </div>
          </div>
          <div class="col-xs-4">
            <div class="input-group">
              <span class="input-group-addon">В</span>
              {% b_input form.height type='number' %}
            </div>
          </div>
          <div class="col-xs-4">
            <div class="input-group">
              <span class="input-group-addon">Т</span>
              {% b_input form.length type='number' %}
            </div>
          </div>
        </div>
        {% b_textarea form.description rows='3' %}
        {% b_choicebox form.danger_category %}
        {% b_textarea form.note rows='3' %}
        <button type="submit" class="btn btn-lg btn-primary btn-block">Заказать</button>
      </form>
    </div>
  </div>
{% endblock %}

{% block ground %}
  {% if form.has_field_errors %}
  <script src="/static/scripts/form_errors.js"></script>
  {% endif %}
  <script src="/static/scripts/choicebox.js"></script>
{% endblock %}

wsgi/openshift/customer/templates/customer/profile.html
{% extends 'base.html' %}

{% block title %}Личный кабинет «Мой Деливери»{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-9">
      <h2>Заказы грузовых перевозок</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-9">
  {% if orders %}
      <table class="table">
        <thead>
          <tr>
            <th>Дата</th>
            <th>Номер</th>
            <th>Откуда</th>
            <th>Куда</th>
            <th>Статус</th>
          </tr>
        </thead>
        <tbody>
    {% for order in orders %}
          <tr>
            <td>{{ order.created_at|date:'j E Y' }}</td>
            <td>{{ order.number }}</td>
            <td>{{ order.dispatch_address }}</td>
            <td>{{ order.delivery_address }}</td>
            <td>{{ order.status }}</td>
          </tr>
    {% endfor %}
        </tbody>
      </table>
  {% else %}
      <p class="lead">Заказов пока нет.</p>
  {% endif %}
    </div>
    <div class="col-md-3">
      <p class="sidebar-btn"><a href="{% url 'customer:order' %}" role="button" class="btn btn-default btn-lg">Заказать доставку &rarr;</a></p>
    </div>
  </div>
  <div class="row">
    <div class="col-md-9">
      <h2>Заявки на таможенные услуги</h2>
    </div>
  </div>
  <div class="row">
    <div class="col-md-9">
  {% if questions %}
      <table class="table">
        <thead>
          <tr>
            <th>Дата</th>
            <th>Номер</th>
            <th>Тип услуги</th>
            <th>Статус</th>
          </tr>
        </thead>
        <tbody>
    {% for question in questions %}
          <tr>
            <td>{{ question.created_at|date:'j E Y' }}</td>
            <td>{{ question.number }}</td>
            <td>{{ question.kind }}</td>
            <td>{{ question.status }}</td>
          </tr>
    {% endfor %}
        </tbody>
      </table>
  {% else %}
      <p class="lead">Заявок пока нет.</p>
  {% endif %}
    </div>
    <div class="col-md-3">
      <p class="sidebar-btn"><a href="{% url 'customer:question' %}" role="button" class="btn btn-default btn-lg">Оставить заявку &rarr;</a></p>
    </div>
  </div>
{% endblock %}

wsgi/openshift/customer/templates/customer/question.html
{% extends 'base.html' %}
{% load boots %}

{% block title %}Онлайн-помощник «Деливери»{% endblock %}

{% block roof %}
  <link href="/static/styles/forms.css" rel="stylesheet">
  {% if form.has_field_errors %}
  <link href="/static/styles/form_errors.css" rel="stylesheet">
  {% endif %}
  <link href="/static/styles/choicebox.css" rel="stylesheet">
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <form role="form" class="form-normal" action="" method="post">{% csrf_token %}
        <h2>Помощь экспертов</h2>
        <p>Опишите вашу проблему и мы поможем найти решение</p>
        {% b_choicebox form.kind 'autofocus' %}
        {% b_textarea form.text rows='10' %}
        <button type="submit" class="btn btn-lg btn-primary btn-block">Отправить</button>
      </form>
    </div>
  </div>
{% endblock %}

{% block ground %}
  {% if form.has_field_errors %}
  <script src="/static/scripts/form_errors.js"></script>
  {% endif %}
  <script src="/static/scripts/choicebox.js"></script>
{% endblock %}

wsgi/openshift/customer/templates/customer/question_complete.html
{% extends 'base.html' %}

{% block title %}Онлайн-помощник «Деливери»{% endblock %}

{% block content %}
  <p class="lead page-informing">Вопрос успешно отправлен эксперту.</p>
{% endblock %}

wsgi/openshift/customer/templates/customer/register.html
{% extends 'base.html' %}
{% load boots %}

{% block title %}Личный кабинет «Мой Деливери»{% endblock %}

{% block roof %}
  <link href="/static/styles/forms.css" rel="stylesheet">
  {% if form.has_field_errors %}
  <link href="/static/styles/form_errors.css" rel="stylesheet">
  {% endif %}
{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
      <form role="form" class="form-solid" action="" method="post">{% csrf_token %}
        <h2>Новый личный кабинет</h2>
  {% if form.non_field_errors %}
        <div id="non_field_alert" class="alert alert-danger alert-dismissable fade in">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    {% for error in form.non_field_errors %}
          <p>{{ error }}</p>
    {% endfor %}
        </div>
  {% endif %}
        {% b_input form.first_name 'autofocus' type='text' spec_class='first' %}
        {% b_input form.last_name type='text' %}
        {% b_input form.email type='email' %}
        {% b_input form.password type='password' %}
        {% b_input form.password_confirm type='password' %}
        {% b_input form.phone type='tel' spec_class='last' %}
        <button type="submit" class="btn btn-lg btn-primary btn-block">Создать</button>
      </form>
    </div>
  </div>
{% endblock %}

{% block ground %}
  {% if form.has_field_errors %}
  <script src="/static/scripts/form_errors.js"></script>
  {% endif %}
{% endblock %}

wsgi/openshift/customer/templates/customer/register_complete.html
{% extends 'base.html' %}

{% block title %}Личный кабинет «Мой Деливери»{% endblock %}

{% block content %}
  <p class="lead page-informing"><a href="{% url 'customer:profile' %}" class="txt">Ваш личный кабинет</a> успешно создан.</p>
{% endblock %}